name: game_utils
description: Various game-related utilities I use in my own projects.
version: 2.0.0
homepage: https://github.com/chrisnorman7/game_utils

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
#  path: ^1.6.0
  meta: ^1.1.8

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
